OutputDir:=nugets

GeneratedPackages = $(wildcard $(OutputDir)/*.nupkg)
PackageBaseNames:=$(basename $(GeneratedPackages))
PackagePubNames:=$(addsuffix .pub,$(PackageBaseNames))

%.pub:
	@echo "-----------------------------------------"
	dotnet nuget push "$(addsuffix .nupkg,$(basename $@))" --source "$(NugetSource)" --skip-duplicate    
	@echo "*************Deployed successfully******************"

deploy: $(PackagePubNames)
	@echo "Start to publish"

.PHONY: deploy


